### ISSUE TITLE
NoClassDefFoundError: io/questdb/client/Sender

### ISSUE THREAD

**Issue by iamkucuk** [questdb/kafka-questdb-connector#2]
Hello all,

When I try to follow the docs here, I concluded that example json configuration:

```
{
    "name": "questdb-sink1",
    "config": {
      "connector.class": "io.questdb.kafka.QuestDBSinkConnector",
      "host": "localhost:9009",
      "topics": "example",
      "table":  "example_table",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "include.key": "false"
    }
  }
```

However, this one throws me that error within Kafka Connect:

```
[2022-11-09 20:53:03,407] INFO EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.questdb.kafka.QuestDBSinkConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = questdb-sink1
	predicates = []
	tasks.max = 1
	transforms = []
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig)
[2022-11-09 20:53:03,409] ERROR Failed to start task questdb-sink1-0 (org.apache.kafka.connect.runtime.Worker)
java.lang.NoClassDefFoundError: io/questdb/client/Sender
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:735)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:146)
	at org.apache.kafka.connect.runtime.TaskConfig.<init>(TaskConfig.java:51)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:510)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1421)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$22(DistributedHerder.java:1434)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: io.questdb.client.Sender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:103)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

	... 15 more
[2022-11-09 20:53:03,413] INFO [Worker clientId=connect-1, groupId=compose-connect-group] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
```

The base docker image I use for Kafka Connect is: `confluentinc/cp-kafka-connect:7.2.2`. Can someone help me out?

**Comment by jerrinot** [comment]
Hello, @iamkucuk, this indicates questdb JAR is missing on Kafka Connect classpath. The ZIP with connector contains 2 JARs:
1. the connect itself
2. questdb jar - this is a dependency of the connector

The stracktrace shows Kafka Connect does not see #2.

**Comment by iamkucuk** [comment]
Hello @jerrinot Thanks for the fast response! I created a docker file that is very close to the one within the repo. Here it is:

```
FROM ubuntu:latest AS builder
WORKDIR /opt
RUN apt-get update && apt-get install -y curl wget unzip jq
RUN curl -s https://api.github.com/repos/questdb/kafka-questdb-connector/releases/latest | jq -r '.assets[]|select(.content_type == "application/zip")|.browser_download_url'|wget -qi -
RUN unzip kafka-questdb-connector-*-bin.zip

FROM confluentinc/cp-kafka-connect:7.2.2

COPY --from=builder /opt/kafka-questdb-connector/*.jar /connector/
ENV CONNECT_PLUGIN_PATH=/connector/
USER 1001
```
What am I missing here?

**Comment by iamkucuk** [comment]
Apparently CONNECT_PLUGIN_PATH is having you install the plugin, but does not make the code reachable. Using as suggested fixed the specific issue.

Here is the example:
`COPY --from=builder /opt/kafka-questdb-connector/*.jar /kafka/connect/questdb-connector/
`
